trigger:
- main

pool:
  name: MylocalPool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run SingleAndroidWeb
  displayName: 'Run npm script: SingleAndroidWeb'

- task: LambdatestResults@1
  inputs:
    connection: 'ankit-LT-connection'  # Make sure this service connection exists
    platform: 'Web Automation'         # Optional: depending on task version
    testType: 'Mocha'                  # Set based on your test framework (e.g., Mocha, Jest, etc.)
    isTunnelActivate: false
    isAppAutomate: false
    isSmartUI: false
