# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  MylocalPool



steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'


#   inputs:
#     connection: 'ankit-LT-connection'
#     isTunnelActivate: false
#     isAppAutomate: false
#     isSmartUI: false

- script: npm install
  displayName: "npm install"
  
- script: npm run SingleAndroidWeb
  displayName: 'npm run commnad and build'
# - script: |
#     npm install
#     npm run build
#     npm run SingleAndroidWeb
#   displayName: 'npm install and build'
