trigger:
- main

pool:
  name: MylocalPool

variables:
  LT_BUILD_NAME: '$(Build.BuildNumber)'  # Default, or override in pipeline variables or UI

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run SingleAndroidWeb
  displayName: 'Run npm script: SingleAndroidWeb'

- task: LambdatestResults@1
  inputs:
    connection: 'ankit-LT-connection'
    platform: 'Web Automation'
    testType: 'Mocha'
    isTunnelActivate: false
    isAppAutomate: false
    isSmartUI: false
    build_name: '$(LT_BUILD_NAME)'
